Config = {}


Config.Distance = 5
Config.Npc = {
	Npc = {
		coords = vector3(1733.24, 3303.68, 41.24),	-- Coords
		NPC = {
			Model = "mp_m_freemode_01",				-- Model mp_m_freemode_01 & mp_f_freemode_01 
			heading = 195.08,						-- NPC Heading
			Text = "∑ ~b~VERIFIED~s~",		 		-- Put whatever u want
			Font = 8,								-- https://wiki.rage.mp/index.php?title=Fonts_and_Colors
			Bar = 370, 								-- Black bar on text
			ScaleX = 0.35,							-- Font Scale X
			ScaleY = 0.35, 							-- Font Scale Y

			UseSecnario = true, 					-- Use Secnario?
			Secnario = "WORLD_HUMAN_AA_SMOKE", 		-- https://github.com/DioneB/gtav-scenarios
			AnimationDirect = "mini@strip_club@private_dance@part1", -- https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt
			AnimationScene = "priv_dance_p1", 		-- https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt

			Cloth = {
				face1 =                      0       ,       --   Face
				skin =                       0       ,       --   Skin
				wrinkles =                   0       ,        --   Wrinkles
				wrinkle_thickness =          0       ,        --   Thickness Of 	Wrinkles
				beard_1 =                    0       ,        --   Bread
				beard_2 =                    0       ,        --   Bread Size
				beard_3 =                    0       ,        --   Bread Color 1
				beard_4 =                    0       ,        --   Bread Color 2
				hair_1 =                     11       ,      -- Hairstyle 1
				hair_2 =                     0       ,        --   Hairstyle 2
				hair_color_1 =               0       ,       --   Hari Color 1
				hair_color_2 =               0       ,       --   Hair Color 2
				eye_color =                  0       ,       --   Eye Color
				eyebrow_type =               0       ,       --   Eyebrow Type
				eyebrow_size =               0       ,       --   Eyebrow Size
				eyebrow_color_1 =            0       ,        --   Eyebrow Color 1
				eyebrow_color_2 =            0       ,        --   Eyebrow Color 2
				makeup_type =                0       ,        --   Makeup Type
				makeup_thickness =           0       ,        --   Make Up Thickness
				makeup_color_1 =             0       ,        --   Makeup Color 1
				makeup_color_2 =             0       ,        --   Makeup Color 2
				lipstick_type =              1       ,        --   Lipstick Type
				lipstick_thickness =         2       ,        --   Lipstick Thickness
				lipstick_color_1 =           0      ,        --   Lipstick Color 1
				lipstick_color_2 =           0       ,        --   Lipstick Color 2
				ears_1 =                     -1       ,       --   Ears 1
				ears_2 =                     0       ,        --   Ears 2
				tshirt_1 =                   0      ,        --   Tshirt 1
				tshirt_2 =                   0       ,        --   Tshirt 2
				torso_1 =                    3       ,      --   Torso 1
				torso_2 =                    5       ,        --   Torso 2
				decals_1 =                   0       ,        --   Decals 1
				decals_2 =                   0       ,        --   Decals 2
				arms =                       1       ,       --   Arms 1
				arms_2 =                     0       ,        --   Arms 2
				pants_1 =                    24       ,       --   Pants 1
				pants_2 =                    0       ,        --   Pants 2
				shoes_1 =                    7       ,       --   Shoes 1
				shoes_2 =                    0       ,        --  Shoes 2
				mask_1 =                     0       ,      --   Mask 1
				mask_2 =                     0       ,        --   Mask 2
				bproof_1 =                   0       ,        --   Bulletproof Vest 1
				bproof_2 =                   0       ,        --   Bulletproof Vest 2
				chain_1 =                    0       ,        --   Chain 1
				chain_2 =                    0       ,        --   Chain 2
				helmet_1 =                   -1       ,       --   Helmet 1
				helmet_2 =                   0       ,        --   Helmet 2
				watches_1 =                  0       ,        --   Watches 1
				watches_2 =                  0       ,        --   Watches 2
				bracelets_1 =                0       ,        --   Bracelets 1
				bracelets_2 =                0       ,        --   Bracelets 2
				glasses_1 =                  0       ,        --   Glasses 1
				glasses_2 =                  0       ,        --   Glasses 2
				bags_1 =                     0       ,        --   Bag 1
				bags_2 =                     0       ,        --   Bag 2 
				blemishes =                  0       ,        --   Blemishes
				blemishes_size=              0       ,        --   Blemishes Size
				ageing =                     0       ,        --   Ageing
				ageing_1 =                   0       ,        --   Ageing 1
				blush =                      0       ,        --   Blush
				blush_1 =                    0       ,        --   Blush 1
				blush_color =                0       ,        --   Blush Color
				complexion =                 0       ,        --   Complexion
				complexion_1 =               0       ,        --   Complexion 1
				sun =                        0       ,        --   Sun
				sun_1 =                      0       ,        --   Sun 1
				freckles =                   0       ,        --   Freckles
				freckles_1 =                 0       ,        --   Freckles Thickness
				chest_hair =                 0       ,        --   Chest Hair
				chest_hair_1 =               0       ,        --   Chest Hair 2
				chest_color =                0       ,        --   Chest Color
				bodyb =                      0       ,        --   Body 1
				bodyb_size =                 0       ,        --   Body Size
			}
		},
	},


	Npc2 = {
		coords = vector3(1731.56, 3304.2, 41.24),	-- Coords
		NPC = {
			Model = "mp_m_freemode_01",				-- Model mp_m_freemode_01 & mp_f_freemode_01 
			heading = 200.24,						-- NPC Heading
			Text = "∑ ~b~VERIFIED~s~",		 		-- Put whatever u want
			Font = 8,								-- https://wiki.rage.mp/index.php?title=Fonts_and_Colors
			Bar = 370, 								-- Black bar on text
			ScaleX = 0.35,							-- Font Scale X
			ScaleY = 0.35, 							-- Font Scale Y

			UseSecnario = true, 					-- Use Secnario?
			Secnario = "WORLD_HUMAN_AA_SMOKE", 		-- https://github.com/DioneB/gtav-scenarios
			AnimationDirect = "mini@strip_club@private_dance@part1", -- https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt
			AnimationScene = "priv_dance_p1", 		-- https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt

			Cloth = {
				face1 =                      0       ,       --   Face
				skin =                       0       ,       --   Skin
				wrinkles =                   0       ,        --   Wrinkles
				wrinkle_thickness =          0       ,        --   Thickness Of 	Wrinkles
				beard_1 =                    0       ,        --   Bread
				beard_2 =                    0       ,        --   Bread Size
				beard_3 =                    0       ,        --   Bread Color 1
				beard_4 =                    0       ,        --   Bread Color 2
				hair_1 =                     11       ,      -- Hairstyle 1
				hair_2 =                     0       ,        --   Hairstyle 2
				hair_color_1 =               0       ,       --   Hari Color 1
				hair_color_2 =               0       ,       --   Hair Color 2
				eye_color =                  0       ,       --   Eye Color
				eyebrow_type =               0       ,       --   Eyebrow Type
				eyebrow_size =               0       ,       --   Eyebrow Size
				eyebrow_color_1 =            0       ,        --   Eyebrow Color 1
				eyebrow_color_2 =            0       ,        --   Eyebrow Color 2
				makeup_type =                0       ,        --   Makeup Type
				makeup_thickness =           0       ,        --   Make Up Thickness
				makeup_color_1 =             0       ,        --   Makeup Color 1
				makeup_color_2 =             0       ,        --   Makeup Color 2
				lipstick_type =              1       ,        --   Lipstick Type
				lipstick_thickness =         2       ,        --   Lipstick Thickness
				lipstick_color_1 =           0      ,        --   Lipstick Color 1
				lipstick_color_2 =           0       ,        --   Lipstick Color 2
				ears_1 =                     -1       ,       --   Ears 1
				ears_2 =                     0       ,        --   Ears 2
				tshirt_1 =                   0      ,        --   Tshirt 1
				tshirt_2 =                   0       ,        --   Tshirt 2
				torso_1 =                    3       ,      --   Torso 1
				torso_2 =                    5       ,        --   Torso 2
				decals_1 =                   0       ,        --   Decals 1
				decals_2 =                   0       ,        --   Decals 2
				arms =                       1       ,       --   Arms 1
				arms_2 =                     0       ,        --   Arms 2
				pants_1 =                    24       ,       --   Pants 1
				pants_2 =                    0       ,        --   Pants 2
				shoes_1 =                    7       ,       --   Shoes 1
				shoes_2 =                    0       ,        --  Shoes 2
				mask_1 =                     0       ,      --   Mask 1
				mask_2 =                     0       ,        --   Mask 2
				bproof_1 =                   0       ,        --   Bulletproof Vest 1
				bproof_2 =                   0       ,        --   Bulletproof Vest 2
				chain_1 =                    0       ,        --   Chain 1
				chain_2 =                    0       ,        --   Chain 2
				helmet_1 =                   -1       ,       --   Helmet 1
				helmet_2 =                   0       ,        --   Helmet 2
				watches_1 =                  0       ,        --   Watches 1
				watches_2 =                  0       ,        --   Watches 2
				bracelets_1 =                0       ,        --   Bracelets 1
				bracelets_2 =                0       ,        --   Bracelets 2
				glasses_1 =                  0       ,        --   Glasses 1
				glasses_2 =                  0       ,        --   Glasses 2
				bags_1 =                     0       ,        --   Bag 1
				bags_2 =                     0       ,        --   Bag 2 
				blemishes =                  0       ,        --   Blemishes
				blemishes_size=              0       ,        --   Blemishes Size
				ageing =                     0       ,        --   Ageing
				ageing_1 =                   0       ,        --   Ageing 1
				blush =                      0       ,        --   Blush
				blush_1 =                    0       ,        --   Blush 1
				blush_color =                0       ,        --   Blush Color
				complexion =                 0       ,        --   Complexion
				complexion_1 =               0       ,        --   Complexion 1
				sun =                        0       ,        --   Sun
				sun_1 =                      0       ,        --   Sun 1
				freckles =                   0       ,        --   Freckles
				freckles_1 =                 0       ,        --   Freckles Thickness
				chest_hair =                 0       ,        --   Chest Hair
				chest_hair_1 =               0       ,        --   Chest Hair 2
				chest_color =                0       ,        --   Chest Color
				bodyb =                      0       ,        --   Body 1
				bodyb_size =                 0       ,        --   Body Size
			}
		},
	},

	Npc3 = {
		coords = vector3(1734.48, 3304.84, 41.24),	-- Coords
		NPC = {
			Model = "mp_m_freemode_01",				-- Model mp_m_freemode_01 & mp_f_freemode_01 
			heading = 200.84,						-- NPC Heading
			Text = "∑ ~b~VERIFIED~s~",		 		-- Put whatever u want
			Font = 8,								-- https://wiki.rage.mp/index.php?title=Fonts_and_Colors
			Bar = 370, 								-- Black bar on text
			ScaleX = 0.35,							-- Font Scale X
			ScaleY = 0.35, 							-- Font Scale Y

			UseSecnario = true, 					-- Use Secnario?
			Secnario = "WORLD_HUMAN_AA_SMOKE", 		-- https://github.com/DioneB/gtav-scenarios
			AnimationDirect = "mini@strip_club@private_dance@part1", -- https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt
			AnimationScene = "priv_dance_p1", 		-- https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt

			Cloth = {
				face1 =                      0       ,       --   Face
				skin =                       0       ,       --   Skin
				wrinkles =                   0       ,        --   Wrinkles
				wrinkle_thickness =          0       ,        --   Thickness Of 	Wrinkles
				beard_1 =                    0       ,        --   Bread
				beard_2 =                    0       ,        --   Bread Size
				beard_3 =                    0       ,        --   Bread Color 1
				beard_4 =                    0       ,        --   Bread Color 2
				hair_1 =                     11       ,      -- Hairstyle 1
				hair_2 =                     0       ,        --   Hairstyle 2
				hair_color_1 =               0       ,       --   Hari Color 1
				hair_color_2 =               0       ,       --   Hair Color 2
				eye_color =                  0       ,       --   Eye Color
				eyebrow_type =               0       ,       --   Eyebrow Type
				eyebrow_size =               0       ,       --   Eyebrow Size
				eyebrow_color_1 =            0       ,        --   Eyebrow Color 1
				eyebrow_color_2 =            0       ,        --   Eyebrow Color 2
				makeup_type =                0       ,        --   Makeup Type
				makeup_thickness =           0       ,        --   Make Up Thickness
				makeup_color_1 =             0       ,        --   Makeup Color 1
				makeup_color_2 =             0       ,        --   Makeup Color 2
				lipstick_type =              1       ,        --   Lipstick Type
				lipstick_thickness =         2       ,        --   Lipstick Thickness
				lipstick_color_1 =           0      ,        --   Lipstick Color 1
				lipstick_color_2 =           0       ,        --   Lipstick Color 2
				ears_1 =                     -1       ,       --   Ears 1
				ears_2 =                     0       ,        --   Ears 2
				tshirt_1 =                   0      ,        --   Tshirt 1
				tshirt_2 =                   0       ,        --   Tshirt 2
				torso_1 =                    3       ,      --   Torso 1
				torso_2 =                    5       ,        --   Torso 2
				decals_1 =                   0       ,        --   Decals 1
				decals_2 =                   0       ,        --   Decals 2
				arms =                       1       ,       --   Arms 1
				arms_2 =                     0       ,        --   Arms 2
				pants_1 =                    24       ,       --   Pants 1
				pants_2 =                    0       ,        --   Pants 2
				shoes_1 =                    7       ,       --   Shoes 1
				shoes_2 =                    0       ,        --  Shoes 2
				mask_1 =                     0       ,      --   Mask 1
				mask_2 =                     0       ,        --   Mask 2
				bproof_1 =                   0       ,        --   Bulletproof Vest 1
				bproof_2 =                   0       ,        --   Bulletproof Vest 2
				chain_1 =                    0       ,        --   Chain 1
				chain_2 =                    0       ,        --   Chain 2
				helmet_1 =                   -1       ,       --   Helmet 1
				helmet_2 =                   0       ,        --   Helmet 2
				watches_1 =                  0       ,        --   Watches 1
				watches_2 =                  0       ,        --   Watches 2
				bracelets_1 =                0       ,        --   Bracelets 1
				bracelets_2 =                0       ,        --   Bracelets 2
				glasses_1 =                  0       ,        --   Glasses 1
				glasses_2 =                  0       ,        --   Glasses 2
				bags_1 =                     0       ,        --   Bag 1
				bags_2 =                     0       ,        --   Bag 2 
				blemishes =                  0       ,        --   Blemishes
				blemishes_size=              0       ,        --   Blemishes Size
				ageing =                     0       ,        --   Ageing
				ageing_1 =                   0       ,        --   Ageing 1
				blush =                      0       ,        --   Blush
				blush_1 =                    0       ,        --   Blush 1
				blush_color =                0       ,        --   Blush Color
				complexion =                 0       ,        --   Complexion
				complexion_1 =               0       ,        --   Complexion 1
				sun =                        0       ,        --   Sun
				sun_1 =                      0       ,        --   Sun 1
				freckles =                   0       ,        --   Freckles
				freckles_1 =                 0       ,        --   Freckles Thickness
				chest_hair =                 0       ,        --   Chest Hair
				chest_hair_1 =               0       ,        --   Chest Hair 2
				chest_color =                0       ,        --   Chest Color
				bodyb =                      0       ,        --   Body 1
				bodyb_size =                 0       ,        --   Body Size
			}
		},
	},
}